# ── GZen.io menu config ────────────────────────────────

[[main]]
  name    = "Blog"
  pageRef = "blog"
  weight  = 10

[[main]]
  name    = "Speaking"
  pageRef = "speaking"
  weight  = 20

[[main]]
  name    = "Resources"
  pageRef = "resources"
  weight  = 30

[[main]]
  name    = "Playground"
  pageRef = "playground"
  weight  = 40

[[main]]
  name    = "About"
  pageRef = "about"
  weight  = 50

[[main]]
  name    = "Donate"
  pageRef = "donate"
  weight  = 60
