# ── GZen.io Blowfish params ──────────────────────────────

colorScheme          = "gzen"
defaultAppearance    = "light"
autoSwitchAppearance = false

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout     = "custom"
  showRecent = false

[article]
  showDate            = true
  showDateUpdated     = false
  showAuthor          = true
  showAuthorBottom    = true
  showReadingTime     = true
  showWordCount       = false
  showTableOfContents = true
  showBreadcrumbs     = true
  showPagination      = true
  showSummary         = true
  showTaxonomies      = true
  showViews           = false
  showLikes           = false
  showZenMode         = false

[list]
  showSummary = true
  showCards = false
  groupByYear = false

[taxonomy]
  showTermCount = true

[term]
  showTableOfContents = false
  groupByYear = false

enableSearch   = false
enableCodeCopy = true
showLikes      = false
showViews      = false

mainSections = ["blog"]
